# Generated by Django 5.2.12 on 2026-04-03 17:18

import church.models.user
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'categorias financeiras',
                'db_table': 'categorias_financeiras',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('carga_horaria', models.PositiveIntegerField(blank=True, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('certificado_template', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_familia', models.CharField(max_length=200)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'famílias',
                'db_table': 'familias',
            },
        ),
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
                ('pastor_presidente', models.CharField(blank=True, max_length=200, null=True)),
                ('data_fundacao', models.DateField(blank=True, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'igreja',
                'verbose_name_plural': 'igreja',
                'db_table': 'igreja',
            },
        ),
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_lideranca', models.CharField(choices=[('pastor', 'Pastor'), ('presbitero', 'Presbítero'), ('diacono', 'Diácono'), ('lider_ministerio', 'Líder de ministério'), ('lider_grupo', 'Líder de grupo'), ('outro', 'Outro')], max_length=30)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('licenciado', 'Licenciado')], default='ativo', max_length=20)),
            ],
            options={
                'verbose_name': 'líder',
                'verbose_name_plural': 'líderes',
                'db_table': 'lideres',
            },
        ),
        migrations.CreateModel(
            name='PequenoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('dia_reuniao', models.CharField(blank=True, choices=[('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10, null=True)),
                ('horario_reuniao', models.TimeField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('data_criacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10)),
            ],
            options={
                'db_table': 'pequenos_grupos',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('nome', models.CharField(max_length=200)),
                ('nivel_acesso', models.CharField(choices=[('admin', 'Admin'), ('pastor', 'Pastor'), ('lider', 'Líder'), ('secretaria', 'Secretaria'), ('financeiro', 'Financeiro'), ('usuario', 'Usuário')], default='usuario', max_length=20)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10)),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', church.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CursoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('matriculado', 'Matriculado'), ('cursando', 'Cursando'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('cancelado', 'Cancelado')], default='matriculado', max_length=20)),
                ('curso', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='church.curso')),
            ],
            options={
                'db_table': 'curso_matriculas',
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_verificacao', models.CharField(max_length=100, unique=True)),
                ('data_emissao', models.DateField()),
                ('arquivo_pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('enviado_email', models.BooleanField(default=False)),
                ('data_envio_email', models.DateTimeField(blank=True, null=True)),
                ('matricula', models.ForeignKey(db_column='matricula_id', on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='church.cursomatricula')),
            ],
            options={
                'db_table': 'certificados',
            },
        ),
        migrations.CreateModel(
            name='CursoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('media_aprovacao', models.DecimalField(decimal_places=2, default=7.0, max_digits=5)),
                ('curso', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='church.curso')),
            ],
            options={
                'db_table': 'curso_modulos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='CursoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('material_apoio', models.CharField(blank=True, max_length=255, null=True)),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('modulo', models.ForeignKey(db_column='modulo_id', on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='church.cursomodulo')),
            ],
            options={
                'db_table': 'curso_aulas',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='CursoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_avaliacao', models.DateField(blank=True, null=True)),
                ('matricula', models.ForeignKey(db_column='matricula_id', on_delete=django.db.models.deletion.CASCADE, related_name='notas_modulos', to='church.cursomatricula')),
                ('modulo', models.ForeignKey(db_column='modulo_id', on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='church.cursomodulo')),
            ],
            options={
                'db_table': 'curso_notas',
            },
        ),
        migrations.CreateModel(
            name='CursoPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula', models.DateField()),
                ('presente', models.BooleanField(default=False)),
                ('aula', models.ForeignKey(db_column='aula_id', on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='church.cursoaula')),
                ('matricula', models.ForeignKey(db_column='matricula_id', on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='church.cursomatricula')),
            ],
            options={
                'db_table': 'curso_presencas',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo_evento', models.CharField(choices=[('culto', 'Culto'), ('conferencia', 'Conferência'), ('retiro', 'Retiro'), ('casamento', 'Casamento'), ('batismo', 'Batismo'), ('reuniao', 'Reunião'), ('outro', 'Outro')], max_length=20)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=255, null=True)),
                ('capacidade_maxima', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_inscricao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imagem_capa', models.CharField(blank=True, max_length=255, null=True)),
                ('publicar_site', models.BooleanField(default=False)),
                ('publicar_app', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('planejamento', 'Planejamento'), ('aberto', 'Aberto'), ('encerrado', 'Encerrado'), ('cancelado', 'Cancelado')], default='planejamento', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eventos',
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_evento', models.DateField(blank=True, null=True)),
                ('capa', models.CharField(blank=True, max_length=255, null=True)),
                ('publicar_app', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(blank=True, db_column='evento_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galerias', to='church.evento')),
            ],
            options={
                'verbose_name_plural': 'galerias',
                'db_table': 'galeria',
            },
        ),
        migrations.CreateModel(
            name='GaleriaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=255)),
                ('legenda', models.CharField(blank=True, max_length=255, null=True)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('galeria', models.ForeignKey(db_column='galeria_id', on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='church.galeria')),
            ],
            options={
                'db_table': 'galeria_fotos',
            },
        ),
        migrations.CreateModel(
            name='HistoricoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabela', models.CharField(max_length=100)),
                ('registro_id', models.PositiveIntegerField()),
                ('acao', models.CharField(choices=[('criacao', 'Criação'), ('atualizacao', 'Atualização'), ('exclusao', 'Exclusão')], max_length=20)),
                ('dados_anteriores', models.JSONField(blank=True, null=True)),
                ('dados_novos', models.JSONField(blank=True, null=True)),
                ('data_acao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_acoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historico_acoes',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(blank=True, max_length=255, null=True)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(db_column='destinatario_id', on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(db_column='remetente_id', on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mensagens',
            },
        ),
        migrations.CreateModel(
            name='Ministerio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10)),
                ('lider', models.ForeignKey(blank=True, db_column='lider_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministerios_lider', to='church.lider')),
                ('vice_lider', models.ForeignKey(blank=True, db_column='vice_lider_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministerios_vice', to='church.lider')),
            ],
            options={
                'verbose_name_plural': 'ministérios',
                'db_table': 'ministerios',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('imagem', models.CharField(blank=True, max_length=255, null=True)),
                ('data_publicacao', models.DateTimeField(blank=True, null=True)),
                ('publicar_site', models.BooleanField(default=False)),
                ('publicar_app', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado'), ('arquivado', 'Arquivado')], default='rascunho', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, db_column='autor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'notícias',
                'db_table': 'noticias',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('membro', 'Membro'), ('visitante', 'Visitante'), ('congregado', 'Congregado')], max_length=20)),
                ('nome', models.CharField(max_length=200)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Nao informado', 'Não informado')], default='Nao informado', max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('profissao', models.CharField(blank=True, max_length=150, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('Casado(a)', 'Casado(a)'), ('Convivente', 'Convivente'), ('Solteiro(a)', 'Solteiro(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viuvo(a)', 'Viúvo(a)')], max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('como_conheceu_igreja', models.TextField(blank=True, null=True)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status_personalizado', models.CharField(blank=True, max_length=100, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cadastrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoas_cadastradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pessoas',
            },
        ),
        migrations.CreateModel(
            name='PequenoGrupoMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10)),
                ('grupo', models.ForeignKey(db_column='grupo_id', on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='church.pequenogrupo')),
                ('pessoa', models.ForeignKey(db_column='pessoa_id', on_delete=django.db.models.deletion.CASCADE, related_name='pequenos_grupos_vinculos', to='church.pessoa')),
            ],
            options={
                'db_table': 'pequeno_grupo_membros',
            },
        ),
        migrations.AddField(
            model_name='pequenogrupo',
            name='anfitriao',
            field=models.ForeignKey(blank=True, db_column='anfitriao_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pequenos_grupos_anfitriao', to='church.pessoa'),
        ),
        migrations.AddField(
            model_name='pequenogrupo',
            name='lider',
            field=models.ForeignKey(blank=True, db_column='lider_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pequenos_grupos_lider', to='church.pessoa'),
        ),
        migrations.AddField(
            model_name='pequenogrupo',
            name='vice_lider',
            field=models.ForeignKey(blank=True, db_column='vice_lider_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pequenos_grupos_vice', to='church.pessoa'),
        ),
        migrations.CreateModel(
            name='PedidoOracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('pedido', models.TextField()),
                ('anonimo', models.BooleanField(default=False)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('orando', 'Orando'), ('respondido', 'Respondido'), ('arquivado', 'Arquivado')], default='pendente', max_length=20)),
                ('pessoa', models.ForeignKey(blank=True, db_column='pessoa_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_oracao', to='church.pessoa')),
            ],
            options={
                'verbose_name_plural': 'pedidos de oração',
                'db_table': 'pedidos_oracao',
            },
        ),
        migrations.CreateModel(
            name='MinisterioMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10)),
                ('ministerio', models.ForeignKey(db_column='ministerio_id', on_delete=django.db.models.deletion.CASCADE, related_name='membros_vinculos', to='church.ministerio')),
                ('pessoa', models.ForeignKey(db_column='pessoa_id', on_delete=django.db.models.deletion.CASCADE, related_name='ministerios_participacoes', to='church.pessoa')),
            ],
            options={
                'db_table': 'ministerio_membros',
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_batismo', models.DateField(blank=True, null=True)),
                ('data_conversao', models.DateField(blank=True, null=True)),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('funcao', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('transferido', 'Transferido'), ('disciplinado', 'Disciplinado'), ('falecido', 'Falecido')], default='ativo', max_length=20)),
                ('pessoa', models.OneToOneField(db_column='pessoa_id', on_delete=django.db.models.deletion.CASCADE, related_name='membro', to='church.pessoa')),
            ],
            options={
                'db_table': 'membros',
            },
        ),
        migrations.AddField(
            model_name='lider',
            name='pessoa',
            field=models.OneToOneField(db_column='pessoa_id', on_delete=django.db.models.deletion.CASCADE, related_name='lider', to='church.pessoa'),
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dizimo', 'Dízimo'), ('oferta', 'Oferta'), ('doacao', 'Doação'), ('saida', 'Saída'), ('outro', 'Outro')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_lancamento', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('metodo_pagamento', models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de crédito'), ('cartao_debito', 'Cartão de débito'), ('pix', 'PIX'), ('transferencia', 'Transferência'), ('cheque', 'Cheque')], max_length=30, null=True)),
                ('comprovante', models.CharField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, db_column='categoria_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='church.categoriafinanceira')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_registrados', to=settings.AUTH_USER_MODEL)),
                ('pessoa', models.ForeignKey(blank=True, db_column='pessoa_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_financeiros', to='church.pessoa')),
            ],
            options={
                'db_table': 'lancamentos_financeiros',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=150)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('data_demissao', models.DateField(blank=True, null=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_contrato', models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'PJ'), ('Voluntario', 'Voluntário'), ('Estagiario', 'Estagiário')], default='Voluntario', max_length=20)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('licenciado', 'Licenciado'), ('demitido', 'Demitido')], default='ativo', max_length=20)),
                ('pessoa', models.OneToOneField(db_column='pessoa_id', on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to='church.pessoa')),
            ],
            options={
                'db_table': 'funcionarios',
            },
        ),
        migrations.CreateModel(
            name='FamiliaMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(choices=[('Pai', 'Pai'), ('Mãe', 'Mãe'), ('Filho(a)', 'Filho(a)'), ('Cônjuge', 'Cônjuge'), ('Outro', 'Outro')], max_length=20)),
                ('familia', models.ForeignKey(db_column='familia_id', on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='church.familia')),
                ('pessoa', models.ForeignKey(db_column='pessoa_id', on_delete=django.db.models.deletion.CASCADE, related_name='familias_vinculos', to='church.pessoa')),
            ],
            options={
                'db_table': 'familia_membros',
            },
        ),
        migrations.AddField(
            model_name='familia',
            name='responsavel',
            field=models.ForeignKey(blank=True, db_column='responsavel_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familias_responsavel', to='church.pessoa'),
        ),
        migrations.CreateModel(
            name='EventoResponsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=100)),
                ('permissoes', models.JSONField(blank=True, null=True)),
                ('evento', models.ForeignKey(db_column='evento_id', on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='church.evento')),
                ('pessoa', models.ForeignKey(db_column='pessoa_id', on_delete=django.db.models.deletion.CASCADE, related_name='eventos_responsabilidades', to='church.pessoa')),
            ],
            options={
                'db_table': 'evento_responsaveis',
            },
        ),
        migrations.CreateModel(
            name='EventoInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pago', models.BooleanField(default=False)),
                ('presente', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('evento', models.ForeignKey(db_column='evento_id', on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='church.evento')),
                ('pessoa', models.ForeignKey(db_column='pessoa_id', on_delete=django.db.models.deletion.CASCADE, related_name='evento_inscricoes', to='church.pessoa')),
            ],
            options={
                'db_table': 'evento_inscricoes',
            },
        ),
        migrations.CreateModel(
            name='Discipulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='em_andamento', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('discipulador', models.ForeignKey(db_column='discipulador_id', on_delete=django.db.models.deletion.CASCADE, related_name='discipulados_como_discipulador', to='church.pessoa')),
                ('discipulo', models.ForeignKey(db_column='discipulo_id', on_delete=django.db.models.deletion.CASCADE, related_name='discipulados_como_discipulo', to='church.pessoa')),
            ],
            options={
                'db_table': 'discipulado',
            },
        ),
        migrations.AddField(
            model_name='cursomatricula',
            name='pessoa',
            field=models.ForeignKey(db_column='pessoa_id', on_delete=django.db.models.deletion.CASCADE, related_name='curso_matriculas', to='church.pessoa'),
        ),
        migrations.AddField(
            model_name='curso',
            name='instrutor',
            field=models.ForeignKey(blank=True, db_column='instrutor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_instruidos', to='church.pessoa'),
        ),
        migrations.CreateModel(
            name='ClasseEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('dia_semana', models.CharField(blank=True, choices=[('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10, null=True)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=255, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('professor', models.ForeignKey(blank=True, db_column='professor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_ensinadas', to='church.pessoa')),
            ],
            options={
                'verbose_name_plural': 'classes de estudo',
                'db_table': 'classes_estudo',
            },
        ),
        migrations.CreateModel(
            name='ClasseAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('concluido', 'Concluído'), ('desistente', 'Desistente')], default='ativo', max_length=20)),
                ('classe', models.ForeignKey(db_column='classe_id', on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='church.classeestudo')),
                ('pessoa', models.ForeignKey(db_column='pessoa_id', on_delete=django.db.models.deletion.CASCADE, related_name='classes_inscricoes', to='church.pessoa')),
            ],
            options={
                'db_table': 'classe_alunos',
            },
        ),
        migrations.CreateModel(
            name='Casal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_casamento', models.DateField(blank=True, null=True)),
                ('familia', models.ForeignKey(blank=True, db_column='familia_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casais', to='church.familia')),
                ('esposa', models.ForeignKey(db_column='esposa_id', on_delete=django.db.models.deletion.CASCADE, related_name='casais_como_esposa', to='church.pessoa')),
                ('esposo', models.ForeignKey(db_column='esposo_id', on_delete=django.db.models.deletion.CASCADE, related_name='casais_como_esposo', to='church.pessoa')),
            ],
            options={
                'db_table': 'casais',
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_primeira_visita', models.DateField(blank=True, null=True)),
                ('data_ultima_visita', models.DateField(blank=True, null=True)),
                ('total_visitas', models.PositiveIntegerField(default=1)),
                ('convertido_membro', models.BooleanField(default=False)),
                ('data_conversao_membro', models.DateField(blank=True, null=True)),
                ('pessoa', models.OneToOneField(db_column='pessoa_id', on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='church.pessoa')),
            ],
            options={
                'db_table': 'visitantes',
            },
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['data_inicio'], name='eventos_data_in_1deeb1_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoacao',
            index=models.Index(fields=['tabela', 'registro_id'], name='historico_a_tabela_17f485_idx'),
        ),
        migrations.AddIndex(
            model_name='pessoa',
            index=models.Index(fields=['tipo'], name='pessoas_tipo_169848_idx'),
        ),
        migrations.AddIndex(
            model_name='pessoa',
            index=models.Index(fields=['nome'], name='pessoas_nome_522284_idx'),
        ),
        migrations.AddIndex(
            model_name='pessoa',
            index=models.Index(fields=['status_personalizado'], name='pessoas_status__f98624_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentofinanceiro',
            index=models.Index(fields=['data_lancamento'], name='lancamentos_data_la_71bd49_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentofinanceiro',
            index=models.Index(fields=['tipo'], name='lancamentos_tipo_8b3ab1_idx'),
        ),
        migrations.AddConstraint(
            model_name='familiamembro',
            constraint=models.UniqueConstraint(fields=('familia', 'pessoa'), name='uniq_familia_membro_pessoa'),
        ),
    ]
