# Generated by Django 5.2.12 on 2026-04-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro')], default='light', help_text='Tema preferido do usuário: claro ou escuro', max_length=10, verbose_name='preferência de tema'),
        ),
    ]
