# Generated by Django 5.2.12 on 2026-04-04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church", "0002_add_theme_preference"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispositivoFCM",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.TextField(unique=True)),
                (
                    "plataforma",
                    models.CharField(
                        choices=[("ios", "iOS"), ("android", "Android")],
                        max_length=10,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="dispositivos_fcm",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dispositivos_fcm",
            },
        ),
    ]
