# Generated by Django 5.2.12 on 2026-04-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_dispositivofcm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoIgreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exibicao', models.CharField(max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('endereco', models.TextField(blank=True)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('site', models.CharField(blank=True, max_length=200)),
                ('pastor_presidente', models.CharField(blank=True, max_length=200)),
                ('data_fundacao', models.DateField(blank=True, null=True)),
                ('logo', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Configuração da Igreja',
                'db_table': 'configuracao_igreja',
            },
        ),
        migrations.AlterField(
            model_name='igreja',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
