# Generated by Django 5.2.12 on 2026-04-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_emailfield_pessoa_igreja'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='codigo_acesso',
            field=models.CharField(blank=True, editable=False, help_text='Código de acesso ao app mobile (gerado automaticamente)', max_length=6, unique=True),
        ),
    ]
