from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView, TokenVerifyView

from church.views_app.mobile_api import (
    admin_dashboard_view,
    auth_codigo_view,
    admin_evento_inscricoes_view,
    admin_financeiro_lancamentos_view,
    admin_membro_detail_view,
    admin_membros_view,
    admin_relatorio_membros_view,
    admin_visitantes_view,
    auth_logout_view,
    auth_token_view,
    chat_contatos_view,
    chat_mensagens_usuario_view,
    chat_ping_view,
    classes_detail_view,
    classes_minhas_view,
    configuracoes_igreja_view,
    curso_matricula_progresso_view,
    curso_matricula_view,
    cursos_detail_view,
    cursos_list_view,
    cursos_minhas_matriculas_view,
    discipulado_meu_view,
    evento_inscricao_status_view,
    evento_inscricao_view,
    eventos_detail_view,
    eventos_list_view,
    familia_minha_view,
    galeria_fotos_view,
    galeria_list_view,
    grupos_detail_view,
    grupos_meus_view,
    membro_me_view,
    ministerios_detail_view,
    ministerios_meus_view,
    noticias_detail_view,
    noticias_list_view,
    oracao_detail_view,
    oracao_view,
    push_dispositivo_view,
)


urlpatterns = [
    path("auth/codigo/", auth_codigo_view, name="api_v1_auth_codigo"),
    path("auth/token/", auth_token_view, name="api_v1_auth_token"),
    path("auth/token/refresh/", TokenRefreshView.as_view(), name="api_v1_auth_refresh"),
    path("auth/token/verify/", TokenVerifyView.as_view(), name="api_v1_auth_verify"),
    path("auth/logout/", auth_logout_view, name="api_v1_auth_logout"),
    path("auth/dispositivo/", push_dispositivo_view, name="api_v1_auth_dispositivo"),
    path("membro/me/", membro_me_view, name="api_v1_membro_me"),
    path("eventos/", eventos_list_view, name="api_v1_eventos"),
    path("eventos/<int:evento_id>/", eventos_detail_view, name="api_v1_eventos_detail"),
    path("eventos/<int:evento_id>/inscricao/", evento_inscricao_view, name="api_v1_evento_inscricao"),
    path(
        "eventos/<int:evento_id>/inscricao/status/",
        evento_inscricao_status_view,
        name="api_v1_evento_inscricao_status",
    ),
    path("noticias/", noticias_list_view, name="api_v1_noticias"),
    path("noticias/<int:noticia_id>/", noticias_detail_view, name="api_v1_noticias_detail"),
    path("grupos/meus/", grupos_meus_view, name="api_v1_grupos_meus"),
    path("grupos/<int:grupo_id>/", grupos_detail_view, name="api_v1_grupos_detail"),
    path("ministerios/meus/", ministerios_meus_view, name="api_v1_ministerios_meus"),
    path("ministerios/<int:ministerio_id>/", ministerios_detail_view, name="api_v1_ministerios_detail"),
    path("cursos/", cursos_list_view, name="api_v1_cursos"),
    path("cursos/<int:curso_id>/", cursos_detail_view, name="api_v1_cursos_detail"),
    path("cursos/minhas-matriculas/", cursos_minhas_matriculas_view, name="api_v1_cursos_matriculas"),
    path("cursos/<int:curso_id>/matricula/", curso_matricula_view, name="api_v1_curso_matricula"),
    path(
        "cursos/matriculas/<int:matricula_id>/progresso/",
        curso_matricula_progresso_view,
        name="api_v1_curso_matricula_progresso",
    ),
    path("discipulado/meu/", discipulado_meu_view, name="api_v1_discipulado_meu"),
    path("classes/minhas/", classes_minhas_view, name="api_v1_classes_minhas"),
    path("classes/<int:classe_id>/", classes_detail_view, name="api_v1_classes_detail"),
    path("familia/minha/", familia_minha_view, name="api_v1_familia_minha"),
    path("oracao/meus/", oracao_view, name="api_v1_oracao_meus"),
    path("oracao/", oracao_view, name="api_v1_oracao"),
    path("oracao/<int:pedido_id>/", oracao_detail_view, name="api_v1_oracao_detail"),
    path("galeria/", galeria_list_view, name="api_v1_galeria"),
    path("galeria/<int:galeria_id>/fotos/", galeria_fotos_view, name="api_v1_galeria_fotos"),
    path("chat/contatos/", chat_contatos_view, name="api_v1_chat_contatos"),
    path("chat/mensagens/<int:usuario_id>/", chat_mensagens_usuario_view, name="api_v1_chat_mensagens"),
    path(
        "chat/mensagens/<int:usuario_id>/lidas/",
        chat_mensagens_usuario_view,
        name="api_v1_chat_mensagens_lidas",
    ),
    path("chat/ping/", chat_ping_view, name="api_v1_chat_ping"),
    path("push/dispositivo/", push_dispositivo_view, name="api_v1_push_dispositivo"),
    # ── Admin ──────────────────────────────────────────────────────────────────
    path("admin/dashboard/", admin_dashboard_view, name="api_v1_admin_dashboard"),
    path("admin/membros/", admin_membros_view, name="api_v1_admin_membros"),
    path("admin/membros/<int:membro_id>/", admin_membro_detail_view, name="api_v1_admin_membro_detail"),
    path("admin/visitantes/", admin_visitantes_view, name="api_v1_admin_visitantes"),
    path("admin/eventos/<int:evento_id>/inscricoes/", admin_evento_inscricoes_view, name="api_v1_admin_evento_inscricoes"),
    path("admin/financeiro/lancamentos/", admin_financeiro_lancamentos_view, name="api_v1_admin_financeiro"),
    path("admin/relatorios/membros/", admin_relatorio_membros_view, name="api_v1_admin_relatorio_membros"),
    path("configuracoes-igreja/", configuracoes_igreja_view, name="api_v1_configuracoes_igreja"),
]
