from django.urls import path

from church.views_app.auth import ChurchLoginView, ChurchLogoutView
from church.views_app.chat_api import chat_enviar, chat_mensagens, chat_ping
from church.views_app.theme_api import user_theme_view, theme_health_check
from church.views_app.comunicacao_views import (
    GaleriaCreateView,
    GaleriaDeleteView,
    GaleriaDetailView,
    GaleriaFotoCreateView,
    GaleriaFotoListView,
    GaleriaListView,
    GaleriaUpdateView,
    MensagemDeleteView,
    MensagemDetailView,
    MensagemListView,
    MensagemNovaView,
    NoticiaCreateView,
    NoticiaDeleteView,
    NoticiaDetailView,
    NoticiaListView,
    NoticiaPortalView,
    NoticiaUpdateView,
    PedidoOracaoCreateView,
    PedidoOracaoDeleteView,
    PedidoOracaoDetailView,
    PedidoOracaoListView,
    PedidoOracaoUpdateView,
)
from church.views_app.config_perfil import (
    ConfiguracoesIndexView,
    ConfiguracoesSistemaView,
    PerfilView,
    UsuarioCreateView,
    UsuarioDeleteView,
    UsuarioListView,
    UsuarioUpdateView,
)
from church.views_app.cursos_views import (
    CertificadoCreateView,
    CertificadoDetailView,
    CertificadoEnviarPlaceholderView,
    CertificadoListView,
    CertificadoUpdateView,
    CursoAulaCreateView,
    CursoAulaListView,
    CursoCreateView,
    CursoDeleteView,
    CursoDetailView,
    CursoListView,
    CursoMatriculaCreateView,
    CursoMatriculaDetailView,
    CursoMatriculaListView,
    CursoMatriculaUpdateView,
    CursoModuloCreateView,
    CursoModuloListView,
    CursoNotaCreateView,
    CursoNotaListView,
    CursoPresencaCreateView,
    CursoPresencaListView,
    CursoUpdateView,
)
from church.views_app.dashboard import DashboardView
from church.views_app.discipulado_classes import (
    ClasseAlunoCreateView,
    ClasseAlunoListView,
    ClasseEstudoCreateView,
    ClasseEstudoDeleteView,
    ClasseEstudoDetailView,
    ClasseEstudoListView,
    ClasseEstudoUpdateView,
    DiscipuladoCreateView,
    DiscipuladoDeleteView,
    DiscipuladoDetailView,
    DiscipuladoListView,
    DiscipuladoUpdateView,
)
from church.views_app.eventos_views import (
    EventoCreateView,
    EventoDeleteView,
    EventoDetailView,
    EventoInscricaoCreateView,
    EventoInscricaoListView,
    EventoInscricaoUpdateView,
    EventoListView,
    EventoResponsavelCreateView,
    EventoResponsavelListView,
    EventoUpdateView,
)
from church.views_app.financeiro_views import (
    CategoriaFinanceiraListView,
    DizimoListView,
    FinanceiroRelatoriosView,
    LancamentoCreateView,
    LancamentoDeleteView,
    LancamentoListView,
    LancamentoUpdateView,
    OfertaListView,
)
from church.views_app.grupos_ministerios import (
    MinisterioCreateView,
    MinisterioDeleteView,
    MinisterioDetailView,
    MinisterioListView,
    MinisterioMembroCreateView,
    MinisterioMembroListView,
    MinisterioUpdateView,
    PequenoGrupoCreateView,
    PequenoGrupoDeleteView,
    PequenoGrupoDetailView,
    PequenoGrupoListView,
    PequenoGrupoMembroCreateView,
    PequenoGrupoMembroListView,
    PequenoGrupoUpdateView,
)
from church.views_app.igreja_familia import (
    CasalCreateView,
    CasalListView,
    FamiliaCreateView,
    FamiliaDetailView,
    FamiliaListView,
    FamiliaMembroCreateView,
    FamiliaMembroListView,
    FamiliaUpdateView,
    IgrejaEditView,
)
from church.views_app.people import (
    FuncionarioCreateView,
    FuncionarioDetailView,
    FuncionarioListView,
    FuncionarioUpdateView,
    LiderCreateView,
    LiderDetailView,
    LiderListView,
    LiderUpdateView,
    MembroCreateView,
    MembroDetailView,
    MembroListView,
    MembroUpdateView,
    VisitanteConverterView,
    VisitanteCreateView,
    VisitanteDetailView,
    VisitanteListView,
    VisitanteUpdateView,
)
from church.views_app.relatorios_views import (
    RelatorioCursosView,
    RelatorioEventosView,
    RelatorioGruposView,
    RelatorioMembrosView,
    RelatorioVisitantesView,
    RelatoriosIndexView,
)

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("login/", ChurchLoginView.as_view(), name="login"),
    path("logout/", ChurchLogoutView.as_view(), name="logout"),
    path("perfil/", PerfilView.as_view(), name="perfil"),
    path("igreja/editar/", IgrejaEditView.as_view(), name="igreja_editar"),
    path("membros/", MembroListView.as_view(), name="membros_listar"),
    path("membros/cadastrar/", MembroCreateView.as_view(), name="membros_cadastrar"),
    path("membros/<int:pk>/", MembroDetailView.as_view(), name="membros_visualizar"),
    path("membros/<int:pk>/editar/", MembroUpdateView.as_view(), name="membros_editar"),
    path("visitantes/", VisitanteListView.as_view(), name="visitantes_listar"),
    path("visitantes/cadastrar/", VisitanteCreateView.as_view(), name="visitantes_cadastrar"),
    path("visitantes/<int:pk>/", VisitanteDetailView.as_view(), name="visitantes_visualizar"),
    path("visitantes/<int:pk>/editar/", VisitanteUpdateView.as_view(), name="visitantes_editar"),
    path(
        "visitantes/<int:pk>/converter/",
        VisitanteConverterView.as_view(),
        name="visitantes_converter",
    ),
    path("lideres/", LiderListView.as_view(), name="lideres_listar"),
    path("lideres/cadastrar/", LiderCreateView.as_view(), name="lideres_cadastrar"),
    path("lideres/<int:pk>/", LiderDetailView.as_view(), name="lideres_visualizar"),
    path("lideres/<int:pk>/editar/", LiderUpdateView.as_view(), name="lideres_editar"),
    path("funcionarios/", FuncionarioListView.as_view(), name="funcionarios_listar"),
    path("funcionarios/cadastrar/", FuncionarioCreateView.as_view(), name="funcionarios_cadastrar"),
    path("funcionarios/<int:pk>/", FuncionarioDetailView.as_view(), name="funcionarios_visualizar"),
    path("funcionarios/<int:pk>/editar/", FuncionarioUpdateView.as_view(), name="funcionarios_editar"),
    path("familias/", FamiliaListView.as_view(), name="familias_listar"),
    path("familias/cadastrar/", FamiliaCreateView.as_view(), name="familias_cadastrar"),
    path("familias/<int:pk>/", FamiliaDetailView.as_view(), name="familias_visualizar"),
    path("familias/<int:pk>/editar/", FamiliaUpdateView.as_view(), name="familias_editar"),
    path("familias/membros/", FamiliaMembroListView.as_view(), name="familias_membros"),
    path("familias/membros/novo/", FamiliaMembroCreateView.as_view(), name="familias_membros_novo"),
    path("familias/casais/", CasalListView.as_view(), name="familias_casais"),
    path("familias/casais/novo/", CasalCreateView.as_view(), name="familias_casais_novo"),
    path("discipulado/", DiscipuladoListView.as_view(), name="discipulado_listar"),
    path("discipulado/cadastrar/", DiscipuladoCreateView.as_view(), name="discipulado_cadastrar"),
    path("discipulado/<int:pk>/", DiscipuladoDetailView.as_view(), name="discipulado_visualizar"),
    path("discipulado/<int:pk>/editar/", DiscipuladoUpdateView.as_view(), name="discipulado_editar"),
    path("discipulado/<int:pk>/excluir/", DiscipuladoDeleteView.as_view(), name="discipulado_excluir"),
    path("classes/", ClasseEstudoListView.as_view(), name="classes_listar"),
    path("classes/cadastrar/", ClasseEstudoCreateView.as_view(), name="classes_cadastrar"),
    path("classes/<int:pk>/", ClasseEstudoDetailView.as_view(), name="classes_visualizar"),
    path("classes/<int:pk>/editar/", ClasseEstudoUpdateView.as_view(), name="classes_editar"),
    path("classes/<int:pk>/excluir/", ClasseEstudoDeleteView.as_view(), name="classes_excluir"),
    path("classes/alunos/", ClasseAlunoListView.as_view(), name="classes_alunos"),
    path("classes/alunos/novo/", ClasseAlunoCreateView.as_view(), name="classes_alunos_novo"),
    path("pequenos-grupos/", PequenoGrupoListView.as_view(), name="pequenos_grupos_listar"),
    path("pequenos-grupos/cadastrar/", PequenoGrupoCreateView.as_view(), name="pequenos_grupos_cadastrar"),
    path("pequenos-grupos/<int:pk>/", PequenoGrupoDetailView.as_view(), name="pequenos_grupos_visualizar"),
    path("pequenos-grupos/<int:pk>/editar/", PequenoGrupoUpdateView.as_view(), name="pequenos_grupos_editar"),
    path("pequenos-grupos/<int:pk>/excluir/", PequenoGrupoDeleteView.as_view(), name="pequenos_grupos_excluir"),
    path("pequenos-grupos/membros/", PequenoGrupoMembroListView.as_view(), name="pequenos_grupos_membros"),
    path(
        "pequenos-grupos/membros/novo/",
        PequenoGrupoMembroCreateView.as_view(),
        name="pequenos_grupos_membros_novo",
    ),
    path("ministerios/", MinisterioListView.as_view(), name="ministerios_listar"),
    path("ministerios/cadastrar/", MinisterioCreateView.as_view(), name="ministerios_cadastrar"),
    path("ministerios/<int:pk>/", MinisterioDetailView.as_view(), name="ministerios_visualizar"),
    path("ministerios/<int:pk>/editar/", MinisterioUpdateView.as_view(), name="ministerios_editar"),
    path("ministerios/<int:pk>/excluir/", MinisterioDeleteView.as_view(), name="ministerios_excluir"),
    path("ministerios/membros/", MinisterioMembroListView.as_view(), name="ministerios_membros"),
    path(
        "ministerios/membros/novo/",
        MinisterioMembroCreateView.as_view(),
        name="ministerios_membros_novo",
    ),
    path("financeiro/lancamentos/", LancamentoListView.as_view(), name="financeiro_lancamentos"),
    path("financeiro/lancamentos/novo/", LancamentoCreateView.as_view(), name="financeiro_lancamento_novo"),
    path(
        "financeiro/lancamentos/<int:pk>/editar/",
        LancamentoUpdateView.as_view(),
        name="financeiro_lancamento_editar",
    ),
    path(
        "financeiro/lancamentos/<int:pk>/excluir/",
        LancamentoDeleteView.as_view(),
        name="financeiro_lancamento_excluir",
    ),
    path("financeiro/dizimos/", DizimoListView.as_view(), name="financeiro_dizimos"),
    path("financeiro/ofertas/", OfertaListView.as_view(), name="financeiro_ofertas"),
    path("financeiro/relatorios/", FinanceiroRelatoriosView.as_view(), name="financeiro_relatorios"),
    path("financeiro/categorias/", CategoriaFinanceiraListView.as_view(), name="financeiro_categorias"),
    path("cursos/", CursoListView.as_view(), name="cursos_listar"),
    path("cursos/cadastrar/", CursoCreateView.as_view(), name="cursos_cadastrar"),
    path("cursos/<int:pk>/", CursoDetailView.as_view(), name="cursos_visualizar"),
    path("cursos/<int:pk>/editar/", CursoUpdateView.as_view(), name="cursos_editar"),
    path("cursos/<int:pk>/excluir/", CursoDeleteView.as_view(), name="cursos_excluir"),
    path("cursos/modulos/", CursoModuloListView.as_view(), name="cursos_modulos"),
    path("cursos/modulos/novo/", CursoModuloCreateView.as_view(), name="cursos_modulos_novo"),
    path("cursos/aulas/", CursoAulaListView.as_view(), name="cursos_aulas"),
    path("cursos/aulas/novo/", CursoAulaCreateView.as_view(), name="cursos_aulas_novo"),
    path("cursos/matriculas/", CursoMatriculaListView.as_view(), name="cursos_matriculas"),
    path("cursos/matriculas/novo/", CursoMatriculaCreateView.as_view(), name="cursos_matriculas_novo"),
    path("cursos/matriculas/<int:pk>/", CursoMatriculaDetailView.as_view(), name="cursos_matricula_detalhe"),
    path(
        "cursos/matriculas/<int:pk>/editar/",
        CursoMatriculaUpdateView.as_view(),
        name="cursos_matricula_editar",
    ),
    path("cursos/presencas/", CursoPresencaListView.as_view(), name="cursos_presencas"),
    path("cursos/presencas/novo/", CursoPresencaCreateView.as_view(), name="cursos_presencas_novo"),
    path("cursos/notas/", CursoNotaListView.as_view(), name="cursos_notas"),
    path("cursos/notas/novo/", CursoNotaCreateView.as_view(), name="cursos_notas_novo"),
    path("cursos/certificados/", CertificadoListView.as_view(), name="cursos_certificados"),
    path("cursos/certificados/novo/", CertificadoCreateView.as_view(), name="cursos_certificados_novo"),
    path(
        "cursos/certificados/<int:pk>/",
        CertificadoDetailView.as_view(),
        name="cursos_certificado_visualizar",
    ),
    path(
        "cursos/certificados/<int:pk>/editar/",
        CertificadoUpdateView.as_view(),
        name="cursos_certificado_editar",
    ),
    path(
        "cursos/certificados/enviar/",
        CertificadoEnviarPlaceholderView.as_view(),
        name="cursos_certificado_enviar",
    ),
    path("eventos/", EventoListView.as_view(), name="eventos_listar"),
    path("eventos/cadastrar/", EventoCreateView.as_view(), name="eventos_cadastrar"),
    path("eventos/<int:pk>/", EventoDetailView.as_view(), name="eventos_visualizar"),
    path("eventos/<int:pk>/editar/", EventoUpdateView.as_view(), name="eventos_editar"),
    path("eventos/<int:pk>/excluir/", EventoDeleteView.as_view(), name="eventos_excluir"),
    path("eventos/responsaveis/", EventoResponsavelListView.as_view(), name="eventos_responsaveis"),
    path(
        "eventos/responsaveis/novo/",
        EventoResponsavelCreateView.as_view(),
        name="eventos_responsaveis_novo",
    ),
    path("eventos/inscricoes/", EventoInscricaoListView.as_view(), name="eventos_inscricoes"),
    path("eventos/inscricoes/novo/", EventoInscricaoCreateView.as_view(), name="eventos_inscricoes_novo"),
    path(
        "eventos/inscricoes/<int:pk>/editar/",
        EventoInscricaoUpdateView.as_view(),
        name="eventos_inscricao_editar",
    ),
    path("noticias/portal/", NoticiaPortalView.as_view(), name="noticias_portal"),
    path("noticias/", NoticiaListView.as_view(), name="noticias_listar"),
    path("noticias/cadastrar/", NoticiaCreateView.as_view(), name="noticias_cadastrar"),
    path("noticias/<int:pk>/", NoticiaDetailView.as_view(), name="noticias_visualizar"),
    path("noticias/<int:pk>/editar/", NoticiaUpdateView.as_view(), name="noticias_editar"),
    path("noticias/<int:pk>/excluir/", NoticiaDeleteView.as_view(), name="noticias_excluir"),
    path("pedidos-oracao/", PedidoOracaoListView.as_view(), name="pedidos_oracao_listar"),
    path("pedidos-oracao/cadastrar/", PedidoOracaoCreateView.as_view(), name="pedidos_oracao_cadastrar"),
    path("pedidos-oracao/<int:pk>/", PedidoOracaoDetailView.as_view(), name="pedidos_oracao_visualizar"),
    path("pedidos-oracao/<int:pk>/editar/", PedidoOracaoUpdateView.as_view(), name="pedidos_oracao_editar"),
    path("pedidos-oracao/<int:pk>/excluir/", PedidoOracaoDeleteView.as_view(), name="pedidos_oracao_excluir"),
    path("galeria/", GaleriaListView.as_view(), name="galeria_listar"),
    path("galeria/cadastrar/", GaleriaCreateView.as_view(), name="galeria_cadastrar"),
    path("galeria/<int:pk>/", GaleriaDetailView.as_view(), name="galeria_visualizar"),
    path("galeria/<int:pk>/editar/", GaleriaUpdateView.as_view(), name="galeria_editar"),
    path("galeria/<int:pk>/excluir/", GaleriaDeleteView.as_view(), name="galeria_excluir"),
    path("galeria/fotos/", GaleriaFotoListView.as_view(), name="galeria_fotos"),
    path("galeria/fotos/novo/", GaleriaFotoCreateView.as_view(), name="galeria_fotos_novo"),
    path("mensagens/", MensagemListView.as_view(), name="mensagens_listar"),
    path("mensagens/nova/", MensagemNovaView.as_view(), name="mensagens_nova"),
    path("mensagens/<int:pk>/", MensagemDetailView.as_view(), name="mensagens_visualizar"),
    path("mensagens/<int:pk>/excluir/", MensagemDeleteView.as_view(), name="mensagens_excluir"),
    path("relatorios/", RelatoriosIndexView.as_view(), name="relatorios_index"),
    path("relatorios/membros/", RelatorioMembrosView.as_view(), name="relatorios_membros"),
    path("relatorios/visitantes/", RelatorioVisitantesView.as_view(), name="relatorios_visitantes"),
    path("relatorios/grupos/", RelatorioGruposView.as_view(), name="relatorios_grupos"),
    path("relatorios/eventos/", RelatorioEventosView.as_view(), name="relatorios_eventos"),
    path("relatorios/cursos/", RelatorioCursosView.as_view(), name="relatorios_cursos"),
    path("configuracoes/", ConfiguracoesIndexView.as_view(), name="configuracoes_index"),
    path("configuracoes/sistema/", ConfiguracoesSistemaView.as_view(), name="configuracoes_sistema"),
    path("configuracoes/usuarios/", UsuarioListView.as_view(), name="configuracoes_usuarios"),
    path("configuracoes/usuarios/novo/", UsuarioCreateView.as_view(), name="configuracoes_usuario_novo"),
    path("configuracoes/usuarios/<int:pk>/editar/", UsuarioUpdateView.as_view(), name="configuracoes_usuario_editar"),
    path(
        "configuracoes/usuarios/<int:pk>/excluir/",
        UsuarioDeleteView.as_view(),
        name="configuracoes_usuario_excluir",
    ),
    path("api/chat/ping/", chat_ping, name="api_chat_ping"),
    path("api/chat/mensagens/", chat_mensagens, name="api_chat_mensagens"),
    path("api/chat/enviar/", chat_enviar, name="api_chat_enviar"),
    path("api/user/theme/", user_theme_view, name="api_user_theme"),
    path("api/health/theme/", theme_health_check, name="api_health_theme"),
]
