# Generated by Django 5.2.12 on 2026-04-06 23:15

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('nome', models.CharField(max_length=200)),
                ('plano', models.CharField(choices=[('basico', 'Básico'), ('pro', 'Pro'), ('premium', 'Premium')], default='basico', max_length=20)),
                ('codigo_acesso', models.CharField(help_text='Código curto para identificação no app (ex: IBMANAUS)', max_length=20, unique=True)),
                ('email_contato', models.EmailField(max_length=254)),
                ('telefone_contato', models.CharField(blank=True, max_length=20)),
                ('responsavel', models.CharField(help_text='Nome do pastor/responsável', max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateField(blank=True, help_text='Vazio = sem expiração', null=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Igreja',
                'verbose_name_plural': 'Igrejas',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.igreja')),
            ],
            options={
                'verbose_name': 'Domínio',
                'verbose_name_plural': 'Domínios',
            },
        ),
    ]
